In [8]:
import numpy as np

a = np.array([[[1,2,3], [3, 2, 5]], [[1,2,3], [3, 2, 5]]])

print(a.shape)
print(a[1])
np.mean(a, axis=1)

(2, 2, 3)
[[1 2 3]
 [3 2 5]]


array([[2., 2., 4.],
       [2., 2., 4.]])

In [9]:
[1,2,3,4][:-1]

[1, 2, 3]

In [2]:
import pandas as pd

df = pd.read_excel("data/labels/nsd_positive_subset.xlsx")

df

,Unnamed: 0,cocoId,cocoSplit,nsdId,file_name,amount_participants,subject,labels
0,0,515102,train2017,72209,train2017/000000515102.jpg,8,NaN,"['toothbrush', 'person']"
1,1,309192,train2017,18505,train2017/000000309192.jpg,8,NaN,"['person', 'hot dog']"
2,2,55184,train2017,21192,train2017/000000055184.jpg,8,NaN,"['tie', 'person']"
3,3,442666,train2017,55107,train2017/000000442666.jpg,8,NaN,"['cell phone', 'person']"
4,4,246166,train2017,70505,train2017/000000246166.jpg,8,NaN,"['cell phone', 'person']"
...,...,...,...,...,...,...,...,...
80,161,449914,train2017,55405,train2017/000000449914.jpg,8,NaN,"['sports ball', 'person', 'baseball glove', 'p..."
81,167,196365,train2017,57648,train2017/000000196365.jpg,8,NaN,"['sports ball', 'person', 'tennis racket']"
82,174,215291,train2017,62544,train2017/000000215291.jpg,8,NaN,"['person', 'surfboard']"
83,176,482858,train2017,63922,train2017/000000482858.jpg,8,NaN,"['umbrella', 'person', 'book', 'book', 'book',..."


In [9]:
import numpy as np

data = np.random.rand(75, 1000)

data_predictions = data

data_predictions = np.random.rand(75, 1000)

data.shape

(75, 1000)

In [18]:
a = data[:, 0]
a.shape

print(np.mean(a))

data.mean(axis=0)[0]

0.548368899099781


np.float64(0.5483688990997808)

In [11]:
residual_sum_squares = np.sum(
    (data - data_predictions) ** 2, axis=0
)
total_sum_squares = np.sum(
    (data - data.mean(axis=0)) ** 2, axis=0
)

print(residual_sum_squares.shape)

print(total_sum_squares.shape)

print(residual_sum_squares)

(1000,)
(1000,)
[11.98461457 16.2517098  16.60175109 11.87392153 11.82917122 13.45832035
 13.76876956 11.773588   13.93328458  8.88658365 13.47218878 13.21653673
 14.72112763 15.13674994 15.5646939  11.10789742 12.51191562 14.69851619
 12.85003569 11.46732601 11.64960034 11.40405109 11.44563636 11.71812694
 11.35524851 14.14668099 13.56555448 12.67625303 11.7025986  10.84442695
 17.26942515 13.48373471 12.8807491  13.64856714 10.3914544   9.25671961
 11.43478694 12.86008951 14.15417901 11.46183248 12.57420433 14.46920323
 14.16180644  9.2985367  11.04577033 12.01629636 13.17726249 12.30045548
 14.51186927 11.98295672 13.18847105 12.05239601 14.78724953 11.74915479
 14.25628641 12.94729304 14.30136609 12.8906191  14.5098746  13.36956994
 13.27120681 14.40296699 11.86291287 16.71617368 11.42094053 13.33031571
  8.79937837 14.3433895   9.49128048 13.46088685 14.35296777 12.33688804
 12.67734006 13.15315898 13.55356852 10.04846698 15.57305602 14.93947386
  9.83276444 14.7088988  13.6898903