In [8]:
import numpy as np

a = np.array([[[1,2,3], [3, 2, 5]], [[1,2,3], [3, 2, 5]]])

print(a.shape)
print(a[1])
np.mean(a, axis=1)

(2, 2, 3)
[[1 2 3]
 [3 2 5]]


array([[2., 2., 4.],
       [2., 2., 4.]])

In [9]:
[1,2,3,4][:-1]

[1, 2, 3]

In [2]:
import pandas as pd

df = pd.read_excel("data/labels/nsd_positive_subset.xlsx")

df

,Unnamed: 0,cocoId,cocoSplit,nsdId,file_name,amount_participants,subject,labels
0,0,515102,train2017,72209,train2017/000000515102.jpg,8,NaN,"['toothbrush', 'person']"
1,1,309192,train2017,18505,train2017/000000309192.jpg,8,NaN,"['person', 'hot dog']"
2,2,55184,train2017,21192,train2017/000000055184.jpg,8,NaN,"['tie', 'person']"
3,3,442666,train2017,55107,train2017/000000442666.jpg,8,NaN,"['cell phone', 'person']"
4,4,246166,train2017,70505,train2017/000000246166.jpg,8,NaN,"['cell phone', 'person']"
...,...,...,...,...,...,...,...,...
80,161,449914,train2017,55405,train2017/000000449914.jpg,8,NaN,"['sports ball', 'person', 'baseball glove', 'p..."
81,167,196365,train2017,57648,train2017/000000196365.jpg,8,NaN,"['sports ball', 'person', 'tennis racket']"
82,174,215291,train2017,62544,train2017/000000215291.jpg,8,NaN,"['person', 'surfboard']"
83,176,482858,train2017,63922,train2017/000000482858.jpg,8,NaN,"['umbrella', 'person', 'book', 'book', 'book',..."


In [4]:
df["cocoId"].to_list()

[515102,
 309192,
 55184,
 442666,
 246166,
 292845,
 107204,
 212380,
 354095,
 61288,
 160181,
 293372,
 355458,
 156084,
 438154,
 209229,
 2372,
 26388,
 413472,
 300622,
 575164,
 239828,
 461187,
 174303,
 455799,
 486503,
 4442,
 16314,
 18367,
 23392,
 64534,
 80084,
 80619,
 92221,
 369171,
 229233,
 139551,
 285588,
 161328,
 485595,
 179914,
 193023,
 338439,
 474024,
 474353,
 167908,
 505643,
 244578,
 526968,
 5028,
 275938,
 544926,
 22964,
 550396,
 559145,
 572215,
 52348,
 577817,
 57796,
 322255,
 10743,
 65400,
 73997,
 569678,
 345751,
 99363,
 103366,
 106107,
 114822,
 388980,
 403789,
 504888,
 150559,
 462134,
 152328,
 417700,
 166504,
 428726,
 73172,
 179480,
 449914,
 196365,
 215291,
 482858,
 354185]